language: groovy

stages:
  - compile
  - test
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: compile
      script: ./gradlew build
    - stage: test
      script: ./gradlew test
    - stage: deploy
      script: skip
      deploy:
        provider: script
        script: ./gradlew bintrayUpload -Dbintray.user=${BINTRAY_USER} -Dbintray.key=${BINTRAY_KEY}
